version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-feedback
    ports:
      - '6530:5432'
    volumes:
      - postgresFeedbackDB:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  postgresFeedbackDB:
