version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-companies
    ports:
      - '6500:5432'
    volumes:
      - postgresCompaniesDB:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  postgresCompaniesDB:
